export const ingredientTranslations: Record<string, string> = {
  "water": "Вода",
  "fragrance": "Отдушка / Парфюм",
  "glycerin": "Глицерин",
  "phenoxyethanol": "Феноксиэтанол",
  "caprylyl glycol": "Каприлилгликоль",
  "tocopherol": "Токоферол (Витамин Е)",
  "limonene": "Лимонен",
  "ethylhexylglycerin": "Этилгексилглицерин",
  "dimethicone": "Диметикон",
  "linalool": "Линалоол",
  "silica": "Диоксид кремния",
  "butylene glycol": "Бутиленгликоль",
  "citric acid": "Лимонная кислота",
  "mica": "Мика (Слюда)",
  "potassium sorbate": "Сорбат калия",
  "caprylic/capric triglyceride": "Каприловый триглицерид",
  "sodium benzoate": "Бензоат натрия",
  "citronellol": "Цитронеллол",
  "tocopheryl acetate": "Токоферилацетат",
  "geraniol": "Гераниол",
  "propanediol": "Пропандиол",
  "sodium hyaluronate": "Гиалуронат натрия",
  "citral": "Цитраль",
  "xanthan gum": "Ксантановая камедь",
  "benzyl alcohol": "Бензиловый спирт",
  "disodium edta": "Динатрий ЭДТА",
  "sodium hydroxide": "Гидроксид натрия",
  "cetearyl alcohol": "Цетеариловый спирт",
  "ci 77492": "Оксид железа (желтый)",
  "panthenol": "Пантенол",
  "benzyl salicylate": "Бензилсалицилат",
  "titanium dioxide (ci 77891)": "Диоксид титана",
  "squalane": "Сквалан",
  "pentylene glycol": "Пентиленгликоль",
  "bht": "БГТ (антиоксидант)",
  "tin oxide": "Оксид олова",
  "talc": "Тальк",
  "alcohol denat.": "Спирт денатурированный",
  "synthetic fluorphlogopite": "Синтетическая слюда",
  "iron oxides (ci 77491)": "Оксид железа (красный)",
  "iron oxides (ci 77499)": "Оксид железа (черный)",
  "benzyl benzoate": "Бензилбензоат",
  "1,2-hexanediol": "1,2-гександиол",
  "alcohol": "Спирт",
  "zinc stearate": "Стеарат цинка",
  "hexyl cinnamal": "Гексил циннамал",
  "hydroxycitronellal": "Гидроксицитронеллаль",
  "sodium chloride": "Хлорид натрия",
  "coumarin": "Кумарин",
  "glyceryl stearate": "Глицерил стеарат",
  "helianthus annuus (sunflower) seed oil": "Масло подсолнечника",
  "alpha-isomethyl ionone": "Альфа-изометил ионон",
  "pentaerythrityl tetra-di-t-butyl hydroxyhydrocinnamate": "Антиоксидант (Pentaerythrityl...)",
  "carbomer": "Карбомер",
  "butyrospermum parkii (shea) butter": "Масло ши",
  "cetyl alcohol": "Цетиловый спирт",
  "stearic acid": "Стеариновая кислота",
  "triethoxycaprylylsilane": "Триэтоксикаприлилсилан",
  "ethylhexyl palmitate": "Этилгексилпальмитат",
  "butyl methoxydibenzoylmethane": "Авобензон (УФ-фильтр)",
  "chlorphenesin": "Хлорфенезин",
  "sodium dehydroacetate": "Дегидроацетат натрия",
  "octyldodecanol": "Октилдодеканол",
  "hexylene glycol": "Гексиленгликоль",
  "lecithin": "Лецитин",
  "propylene glycol": "Пропиленгликоль",
  "isododecane": "Изододекан",
  "simmondsia chinensis (jojoba) seed oil": "Масло жожоба",
  "polysorbate 20": "Полисорбат 20",
  "polyethylene": "Полиэтилен",
  "sodium citrate": "Цитрат натрия",
  "boron nitride": "Нитрид бора",
  "eugenol": "Эвгенол",
  "ethylhexyl methoxycinnamate": "Октиноксат (УФ-фильтр)",
  "lactic acid": "Молочная кислота",
  "camellia sinensis leaf extract": "Экстракт зеленого чая",
  "octyldodecyl stearoyl stearate": "Октилдодецил стеароил стеарат",
  "niacinamide": "Ниацинамид",
  "aloe barbadensis leaf juice": "Сок алоэ вера",
  "cyclopentasiloxane": "Циклопентасилоксан",
  "disteardimonium hectorite": "Дистеардимониум гекторит",
  "kaolin": "Каолин",
  "hydrogenated polyisobutene": "Гидрогенизированный полиизобутен",
  "lauroyl lysine": "Лауроил лизин",
  "diisostearyl malate": "Диизостеарил малат",
  "ethylhexyl salicylate": "Этилгексилсалицилат",
  "sorbic acid": "Сорбиновая кислота",
  "caffeine": "Кофеин",
  "maltodextrin": "Мальтодекстрин",
  "trimethylsiloxysilicate": "Триметилсилоксисиликат",
  "hydroxyethylcellulose": "Гидроксиэтилцеллюлоза"
};


export const allergenOptions = Object.entries(ingredientTranslations)
  .map(([value, label]) => ({
    value,
    label,
  }))
  .sort((a, b) => a.label.localeCompare(b.label));